[tool.poetry]
name = "lifetimes"
version = "0.1.0"
description = "Tool to determine mode lifetimes in datasets"
packages = [{ include = "lifetimes", from = "src" }]
authors = ["Fabian Emmerich <fabian.emmerich@4-cast.de>"]

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
numpy = "^1.21.4"
xarray = "^0.20.2"
netCDF4 = "^1.5.8"
dask = {extras = ["distributed"], version = "^2022.2.0"}
dask-jobqueue = "^0.7.3"
scikit-learn = "^1.0.2"
matplotlib = "^3.5.1"
ipyparallel = "^8.2.0"
bokeh = "^2.4.2"
mlflow = "^1.27.0"
boto3 = {version = "^1.23.0", optional = true}
sagemaker = {version = "^2.89.0", optional = true}
mantik = "^0.1.0"
jupyter = {version = "^1.0.0", optional = true}
hdbscan = "^0.8.28"
seaborn = "^0.11.2"
python-dotenv = {version = "^0.20.0", optional = true}

[tool.poetry.extras]
mlflow = ["boto3", "sagemaker"]
notebooks = ["jupyter", "python-dotenv"]

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
pre-commit = "^2.17.0"
pytest-cov = "^3.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
addopts = "--cov=lifetimes --cov-report term-missing"

[tool.black]
line-length = 80

