[tool.poetry]
name = "lifetimes"
version = "0.1.0"
description = "Tool to determine mode lifetimes in datasets"
packages = [{ include = "lifetimes", from = "src" }]
authors = ["Fabian Emmerich <fabian.emmerich@4-cast.de>"]

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
numpy = "^1.21.4"
xarray = "^0.20.2"
netCDF4 = "^1.5.8"
dask = "^2021.12.0"
scikit-learn = "^1.0.2"
jupyter = {version = "^1.0.0", extras = ["notebooks"]}
matplotlib = {version = "^3.5.1", extras = ["notebooks"]}

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
pre-commit = "^2.16.0"
pytest-cov = "^3.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
addopts = "--cov=lifetimes --cov-report term-missing"
