Environment:
    Singularity:
      Path: /p/project/deepacf/emmerich1/vissl.sif
      Type: remote
UnicoreApiUrl: https://zam2125.zam.kfa-juelich.de:9112/JUWELS/rest/core
Resources:
  Runtime: 6h
  Queue: develbooster
  Nodes: 1
  #NodeConstraints: largedata
Exclude:
  - "*.sif"
  - "README.md"
