UnicoreApiUrl: https://zam2125.zam.kfa-juelich.de:9112/JUWELS/rest/core
Environment:
  Apptainer:
    Path: /p/project/deepacf/maelstrom/emmerich1/a6-cuda.sif
    Type: remote
  Variables:
    OMP_NUM_THREADS: 1
Resources:
  Runtime: 6h
  Queue: booster
  Nodes: 1
  #NodeConstraints: largedata
Exclude: ["*.sif"]
