UnicoreApiUrl: https://zam2125.zam.kfa-juelich.de:9112/JUWELS/rest/core
Environment:
    Apptainer:
      Path: /p/project/deepacf/maelstrom/emmerich1/a6.sif
      Type: remote
Resources:
  Runtime: 1h
  Queue: develbooster
  Nodes: 1
  GPUsPerNode: 1
  #NodeConstraints: largedata
Exclude: ["*.sif"]
